name: Fetch TLE from CelesTrak

on:
  schedule:
    # Запускать в 0 минут каждые 12 часов (например, 00:00 и 12:00 UTC)
    - cron: '0 */12 * * *'
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create data directory
        run: mkdir -p data

      - name: Download TLE data
        run: |
          GROUPS=("stations" "noaa" "visual" "active" "last-30-days")
          for GROUP in "${GROUPS[@]}"; do
            echo "Downloading $GROUP..."
            curl -s -o "data/${GROUP}.txt" "https://celestrak.org/NORAD/elements/gp.php?GROUP=${GROUP}&FORMAT=tle"
            sleep 1
          done

      - name: Commit and Push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/*.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: auto-update TLE data" && git push)

